
# Build matrix
language: node_js
matrix:
  include:

    # Run linter once
    - node_js: '7'
      env:
        - LINT=true

    # Run browser tests
    - node_js: '7'
      env:
        - SAUCE=true

    # Run tests
    - node_js: '0.10'
    - node_js: '0.12'
    - node_js: '4'
    - node_js: '5'
    - node_js: '6'
    - node_js: '7'

  # Allow Sauce Labs tests to fail
  allow_failures:
    - env:
        - SAUCE=true

# Environment variables
env:
  global:
    - secure: "tmKphgbrLOSn8QzyynW4QXG+wL4i0rtjdGJ9V1g97msQplvTWd8VRynhcinyjMBuDA+SsCLrMPYniSXFwoCFOFBd/MT4G9U3N1VBMPOuBdWq3EhXPsN6h1IGHIGgjU8G6Ntw1CDC6gTvp0qivHvMgn/uPN/O3+1lYkL8F+WtUnw="
    - secure: "yS1Itt0q435UIl6n23hURQsx8YOy1cP1V1N60KAUEccCiALN/uRccKbeKCFEMBud0VVx9DdaF5q0PVRxxwJdoedpmG4S+59WH/IKo3Co3zdLuamZcH6cV2rur1PAQjMBK+y/RifE6Z++63PpjtdozsVIBbFcjPKKWsWQzRXzIk8="

# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# Before install
before_install:
  - npm install coveralls

# Build script
script:
  - 'if [ $LINT ]; then make verify; fi'
  - 'if [ $SAUCE ]; then ./node_modules/.bin/zuul -ui mocha-bdd -- test/unit/lib/proclaim.js; fi'
  - 'if [ ! $LINT ] && [ ! $SAUCE ]; then make test; fi'
  - 'if [ ! $LINT ] && [ ! $SAUCE ]; then cat ./coverage/lcov.info | ./node_modules/.bin/coveralls || true; fi'
