ui: mocha-bdd
browsers:
  - name: iphone
    version: [oldest..latest]
  - name: ipad
    version: [oldest..latest]
  - name: firefox
    version: [oldest..latest]
  - name: safari
    version: [oldest..latest]
  - name: chrome
    version: [oldest..latest]
  - name: internet explorer
    version: [oldest..latest]
  - name: microsoftedge
    version: [oldest..latest]
  - name: opera
    version: [oldest..latest]
  - name: android
    version: [oldest..latest]
scripts:
  - "./lib/proclaim.js"
